# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jastics Labs
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

email: info@jastics.com

# Social links
linkedin_url: https://www.linkedin.com/company/11286826/
twitter_url: https://twitter.com/jastics
upwork_url:  https://www.upwork.com/agencies/~013609ed8111b7920c
instagram_url: https://www.instagram.com/jasticslabs/

paginate: 5
paginate_path: "/blog/page/:num/"

disqus:
  comments: true
  shortname: https-jastics-com

collections:
  whitepapers:
    output: true    
  expertise:
    output: false


defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      page_type: post

  - scope:
      path: ""
      type: whitepapers
    values:
      layout: post
      page_type: whitepaper

sass:
  style: compressed      

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
